### ISSUE TITLE
distribution not found after os-update

### ISSUE THREAD

**Issue by nobody333** [cockroach/episoder#10]
Hello,
I recently update from fedora 28 to 29 which had python updated to 3.7.2.
Whenever I run episoder I get the following error:

Traceback (most recent call last):
  File "/usr/bin/episoder", line 4, in <module>
    __import__('pkg_resources').run_script('episoder==0.8.3', 'episoder')
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3112, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3096, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3125, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'episoder==0.8.3' distribution was not found and is required by the application

If i switch from python 3 to python 2, episoder runs as expected, but I get the UnicodeEncodeError on some shows (see the last isssue I created).
How can I fix the DistributionNotFound?

Thanks in advance.

**Comment by nobody333** [comment]
I had a few minutes to investigate the issue today. The problem was an outdated pip setup, that I was carrying over from before the OS-update. I only needed to update the distribute-script:
#pip install --upgrade setuptools
#pip install --upgrade distribute
This solved the Issue for me.
