### ISSUE TITLE
Unicode errors on "episoder list"

### ISSUE THREAD

**Issue by GarryG** [cockroach/episoder#11]
Episoder has problems when show episodes contain unicode characters ...
E.g., currently the Daily Show episode for 11th of July has this in the title:

15|79|2019-07-11|0|Your Moment of Them: The Best of Dulcé Sloan Vol. 2|79|UNK|

This causes this crash:

Traceback (most recent call last):
  File "/usr/local/bin/episoder", line 4, in <module>
    __import__('pkg_resources').run_script('episoder==0.8.3', 'episoder')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/episoder-0.8.3-py2.7.egg/EGG-INFO/scripts/episoder", line 470, in <module>

  File "/usr/local/lib/python2.7/dist-packages/episoder-0.8.3-py2.7.egg/EGG-INFO/scripts/episoder", line 467, in main

  File "/usr/local/lib/python2.7/dist-packages/episoder-0.8.3-py2.7.egg/EGG-INFO/scripts/episoder", line 429, in episodes

  File "build/bdist.linux-x86_64/egg/pyepisoder/output.py", line 104, in render
  File "build/bdist.linux-x86_64/egg/pyepisoder/output.py", line 78, in _render
  File "build/bdist.linux-x86_64/egg/pyepisoder/output.py", line 39, in format
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 37: ordinal not in range(128)

**Comment by GarryG** [comment]
After altering the title of the episode, list output works fine.

**Comment by cockroach** [comment]
I can't seem to reproduce this on my machine. Would you mind posting your locale settings?

**Comment by GarryG** [comment]
root@dck:~# locale
LANG=en_US
LANGUAGE=en_US
LC_CTYPE="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_COLLATE="en_US"
LC_MONETARY="en_US"
LC_MESSAGES="en_US"
LC_PAPER="en_US"
LC_NAME="en_US"
LC_ADDRESS="en_US"
LC_TELEPHONE="en_US"
LC_MEASUREMENT="en_US"
LC_IDENTIFICATION="en_US"
LC_ALL=

Just did a test:

Altered an entry like this: (was an existing entry)
update episodes set title="Test äöüéè"  where show_id=15 and num=138   limit 1;

got the same error. Remove the "éè" characters, still the same error.

**Comment by cockroach** [comment]
Ah, this is probably the same issue as #8 . Could you please try if you get the same result with Python 3?
