### ISSUE TITLE
"episoder update" for shows without broadcast dates/episodes causes errors

### ISSUE THREAD

**Issue by GarryG** [cockroach/episoder#12]
While searching and adding of new shows works fine (e.G. "nExt (2019)" or "Picard"), running an update for those shows (which I presume have no episode listing yet) causes errors:

ERROR:Episoder:Error parsing Show: Star Trek: Picard
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/episoder-0.8.3-py2.7.egg/EGG-INFO/scripts/episoder", line 291, in update
  File "build/bdist.linux-x86_64/egg/pyepisoder/sources.py", line 258, in parse
    return self._state.parse(show, db, args.agent)
  File "build/bdist.linux-x86_64/egg/pyepisoder/sources.py", line 225, in parse
    episodes = sorted(self._fetch_episodes(show, 1, user_agent))
  File "build/bdist.linux-x86_64/egg/pyepisoder/sources.py", line 192, in _fetch_episodes
    (data, links) = self._get_episodes(show, page, agent)
  File "build/bdist.linux-x86_64/egg/pyepisoder/sources.py", line 156, in _get_episodes
    result = self._get("series/%d/episodes" % show_id, opts, agent)
  File "build/bdist.linux-x86_64/egg/pyepisoder/sources.py", line 148, in _get
    raise TVDBShowNotFoundError(data.get("Error"))
TVDBShowNotFoundError: No results for your query: map[tve.seriesId:364093]

**Comment by cockroach** [comment]
Thank you for reporting this issue, the development branch should now contain a patch that fixes it.

**Comment by GarryG** [comment]
Thanks, can confirm that the errors I got are fixed with the latest development version.

**Comment by cockroach** [comment]
A new release 0.8.5 with this fix is now available on pypi
