### ISSUE TITLE
Errors with "episoder list -d 2017-07-04 -n 90" after update

### ISSUE THREAD

**Issue by krg1966** [cockroach/episoder#6]
Since update yesterday, when I issue the command "episoder list -d 2017-07-04 -n 90", I'm getting the following errors after approximately 27 days of shows are listed:

Traceback (most recent call last):
  File "/usr/bin/episoder", line 470, in <module>
    main()
  File "/usr/bin/episoder", line 467, in main
    func()
  File "/usr/bin/episoder", line 429, in episodes
    out.render(episodes, not self._args.nocolor)
  File "/usr/lib/python3.6/site-packages/pyepisoder/output.py", line 104, in render
    self._render(episode, render, color)
  File "/usr/lib/python3.6/site-packages/pyepisoder/output.py", line 78, in _render
    render(self.format(episode), color)
  File "/usr/lib/python3.6/site-packages/pyepisoder/output.py", line 39, in format
    string = string.replace("%eptitle", episode.title)
TypeError: replace() argument 2 must be str, not None

Any help to troubleshoot would be appreciated.  I've checked depencies listed in AUR and they are all installed.  I'm using manjaro-xfce.

**Comment by krg1966** [comment]
Thanks I saw this but didn't realize it was the issue I was encountering.

Sent from my iPhone

On Jul 6, 2017, at 6:50 PM, cockroach <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #6<https://github.com/cockroach/episoder/issues/6> via 2f630c9<https://github.com/cockroach/episoder/commit/2f630c985672e8eac46dcc382aa77927e7b0a705>.
