### ISSUE TITLE
Python 2: UnicodeEncodeError after updating from 0.7.3 to 0.8.3

### ISSUE THREAD

**Issue by nobody333** [cockroach/episoder#8]
Hallo,
I updated episoder this morning and now I get the following error message:
[nobody333@server-fedora ~]$ episoder list
......
Wed, Nov 01, 2017 The Shannara Chronicles 2x04 - Dweller
Traceback (most recent call last):
  File "/usr/bin/episoder", line 4, in <module>
    __import__('pkg_resources').run_script('episoder==0.8.3', 'episoder')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 741, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1509, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/episoder-0.8.3-py2.7.egg/EGG-INFO/scripts/episoder", line 470, in <module>
    
  File "/usr/lib/python2.7/site-packages/episoder-0.8.3-py2.7.egg/EGG-INFO/scripts/episoder", line 467, in main
    
  File "/usr/lib/python2.7/site-packages/episoder-0.8.3-py2.7.egg/EGG-INFO/scripts/episoder", line 429, in episodes
    
  File "build/bdist.linux-x86_64/egg/pyepisoder/output.py", line 104, in render
  File "build/bdist.linux-x86_64/egg/pyepisoder/output.py", line 78, in _render
  File "build/bdist.linux-x86_64/egg/pyepisoder/output.py", line 39, in format
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 3: ordinal not in range(128)

The error was introduced in 0.8.2. 0.8.1 is working fine.

Thanks in advance.

**Comment by cockroach** [comment]
Hi

This looks annoying. Do you happen to know which show is causing the problem?

**Comment by nobody333** [comment]
Hi,
seems to be random - I get the same error today, when I replace the 0.8.1 binary with 0.8.2 oder 0.8.2.
So the show doessn't seem to mather.

**Comment by cockroach** [comment]
Okay, I seem to be able to reproduce it now, it only happens with Python version 2 though.

Just to confirm that this is the same issue, could you try running episoder with Python 3?

**Comment by nobody333** [comment]
Hallo,
replacing python 2 with python 3 did the trick. I can use 0.8.3 with python 3 without the UnicodeError.
Thank you for the help.

**Comment by cockroach** [comment]
Thanks, in this case I know what the problem is. Unfortunately character encoding is a bit of a mess in Python 2, I'll have to see whether I can find some workaround.

**Comment by polyzen** [comment]
\*cough\* https://github.com/numpy/numpy/blob/master/doc/neps/dropping-python2.7-proposal.rst

Also regarding 2.6 support: https://github.com/collective/icalendar/pull/246

**Comment by cockroach** [comment]
Thanks, good to know.
