### ISSUE TITLE
recent error

### ISSUE THREAD

**Issue by 0xygen8** [cockroach/episoder#9]
it worked fine for some time,... now I get this error:
I started fresh on a fresh container to rule out library errrors (did something change @ thetvdb?)

0xygen8@sixty3:~/episoder$ episoder add [random]
No config file found, using defaults
0xygen8@sixty3:~/episoder$ episoder update
No config file found, using defaults
ERROR:Episoder:Error parsing Show: [random]
Traceback (most recent call last):
  File "/usr/local/bin/episoder", line 291, in update
    parser.parse(show, database, self._args)
  File "/usr/local/lib/python3.5/dist-packages/pyepisoder/sources.py", line 258, in parse
    return self._state.parse(show, db, args.agent)
  File "/usr/local/lib/python3.5/dist-packages/pyepisoder/sources.py", line 225, in parse
    episodes = sorted(self._fetch_episodes(show, 1, user_agent))
  File "/usr/local/lib/python3.5/dist-packages/pyepisoder/sources.py", line 192, in _fetch_episodes
    (data, links) = self._get_episodes(show, page, agent)
  File "/usr/local/lib/python3.5/dist-packages/pyepisoder/sources.py", line 156, in _get_episodes
    result = self._get("series/%d/episodes" % show_id, opts, agent)
  File "/usr/local/lib/python3.5/dist-packages/pyepisoder/sources.py", line 145, in _get
    data = response.json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by cockroach** [comment]
Yes, this seems to be an issue with thetvdb, I am getting the same errors.

There is a [thread about this on their forums](https://forums.thetvdb.com/viewtopic.php?f=17&p=128267); I don't think there is anything I can do at the moment.

**Comment by 0xygen8** [comment]
Wow that is a quick and complete answer. Since this is an upstream issue you may close it here. Thanks

**Comment by cockroach** [comment]
I think I'll leave it open for now, in case anyone else wonders…

**Comment by cockroach** [comment]
The API seems to work again, I'll close this now.
